<?php

$dictionary['zd_Tickets'] = array(
	'table'=>'zd_tickets',
	'audited'=>true,
	'fields'=>array (
  'status' => 
  array (
    'name' => 'status',
    'vname' => 'LBL_STATUS',
    'type' => 'enum',
    'options' => 'status_list',
    'len' => 100,
    'audited' => true,
    'comment' => 'The status of the issue',
    'merge_filter' => 'enabled',
    'required' => false,
    'massupdate' => 0,
    'default' => 'New',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'reportable' => true,
    'calculated' => false,
    'size' => '20',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'priority' => 
  array (
    'name' => 'priority',
    'vname' => 'LBL_PRIORITY',
    'type' => 'enum',
    'options' => 'priority_list',
    'len' => 100,
    'audited' => true,
    'comment' => 'An indication of the priority of the issue',
    'merge_filter' => 'enabled',
    'required' => false,
    'massupdate' => 0,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'reportable' => true,
    'calculated' => false,
    'size' => '20',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'type' => 
  array (
    'name' => 'type',
    'vname' => 'LBL_TYPE',
    'type' => 'enum',
    'options' => 'type_list',
    'len' => 100,
    'comment' => 'The type of issue',
    'merge_filter' => 'enabled',
    'required' => false,
    'massupdate' => 0,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'size' => '20',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'nice_id' => 
  array (
    'required' => false,
    'name' => 'nice_id',
    'vname' => 'LBL_NICE_ID',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'disable_num_format' => '',
  ),
  'tags' => 
  array (
    'required' => false,
    'name' => 'tags',
    'vname' => 'LBL_TAGS',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'requester_email' => 
  array (
    'required' => false,
    'name' => 'requester_email',
    'vname' => 'LBL_REQUESTER_EMAIL',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'requester_id' => 
  array (
    'required' => false,
    'name' => 'requester_id',
    'vname' => 'LBL_REQUESTER_ID',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'disable_num_format' => '',
  ),
  'requester_name' => 
  array (
    'required' => false,
    'name' => 'requester_name',
    'vname' => 'LBL_REQUESTER_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'created_at' => 
  array (
    'required' => false,
    'name' => 'created_at',
    'vname' => 'LBL_CREATED_AT',
    'type' => 'datetimecombo',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'size' => '20',
    'dbType' => 'datetime',
  ),
  'updated_at' => 
  array (
    'required' => false,
    'name' => 'updated_at',
    'vname' => 'LBL_UPDATED_AT',
    'type' => 'datetimecombo',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'size' => '20',
    'dbType' => 'datetime',
  ),
  'assigned_at' => 
  array (
    'required' => false,
    'name' => 'assigned_at',
    'vname' => 'LBL_ASSIGNED_AT',
    'type' => 'datetimecombo',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'size' => '20',
    'dbType' => 'datetime',
  ),
  'solved_at' => 
  array (
    'required' => false,
    'name' => 'solved_at',
    'vname' => 'LBL_SOLVED_AT',
    'type' => 'datetimecombo',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'size' => '20',
    'dbType' => 'datetime',
  ),
  'score' => 
  array (
    'required' => false,
    'name' => 'score',
    'vname' => 'LBL_SCORE',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'disable_num_format' => '',
  ),
  'due_date' => 
  array (
    'required' => false,
    'name' => 'due_date',
    'vname' => 'LBL_DUE_DATE',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'size' => '20',
  ),
  'via' => 
  array (
    'name' => 'via',
    'vname' => 'LBL_VIA',
    'type' => 'enum',
    'options' => 'via_list',
    'len' => 100,
    'comment' => 'The origin of the ticket',
    'merge_filter' => 'enabled',
    'required' => false,
    'massupdate' => 0,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'size' => '20',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'subject' => 
  array (
    'required' => false,
    'name' => 'subject',
    'vname' => 'LBL_SUBJECT',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'group_id' => 
  array (
    'required' => false,
    'name' => 'group_id',
    'vname' => 'LBL_GROUP_ID',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'disable_num_format' => '',
  ),
  'group_name' => 
  array (
    'required' => false,
    'name' => 'group_name',
    'vname' => 'LBL_GROUP_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'assignee_id' => 
  array (
    'required' => false,
    'name' => 'assignee_id',
    'vname' => 'LBL_ASSIGNEE_ID',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'disable_num_format' => '',
  ),
  'assignee_name' => 
  array (
    'required' => false,
    'name' => 'assignee_name',
    'vname' => 'LBL_ASSIGNEE_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'organization_id' => 
  array (
    'required' => false,
    'name' => 'organization_id',
    'vname' => 'LBL_GROUP_ID',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'disable_num_format' => '',
  ),
  'organization_name' => 
  array (
    'required' => false,
    'name' => 'organization_name',
    'vname' => 'LBL_ORGANIZATION_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'cc_list' => 
  array (
    'required' => false,
    'name' => 'cc_list',
    'vname' => 'LBL_CC_LIST',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'can_update' => 
  array (
    'required' => false,
    'name' => 'can_update',
    'vname' => 'LBL_CAN_UPDATE',
    'type' => 'bool',
    'massupdate' => '0',
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
    'id' => 'can_update',
  ),
  'can_edit_tags' => 
  array (
    'required' => false,
    'name' => 'can_edit_tags',
    'vname' => 'LBL_CAN_EDIT_TAGS',
    'type' => 'bool',
    'massupdate' => '0',
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
    'id' => 'can_edit_tags',
  ),
  'can_comment' => 
  array (
    'required' => false,
    'name' => 'can_comment',
    'vname' => 'LBL_CAN_COMMENT',
    'type' => 'bool',
    'massupdate' => '0',
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
    'id' => 'can_comment',
  ),
  'can_public_comment' => 
  array (
    'required' => false,
    'name' => 'can_public_comment',
    'vname' => 'LBL_CAN_PUBLIC_COMMENT',
    'type' => 'bool',
    'massupdate' => '0',
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
    'id' => 'can_public_comment',
  ),
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('zd_Tickets','zd_Tickets', array('basic','assignable'));
